[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
ignore = []

[licenses]
unlicensed = "deny"
allow = ["MIT", "Apache-2.0"]
copyleft = "deny"

[bans]
multiple-versions = "deny"
highlight = "all"


[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index"
]
allow-git = [
]
